# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12544c5f19344d16c4530df0a029c407a22db670bcf010ee79877c9afcaafac931c2c6729b02571ef47d330cc56a43caece784fe8162b70164c5014b7a0594f8

test:
  secret_key_base: f417d47f0b03abe9cfbcc699b4466bae2da42553c11453d6515aebd490732cc293e3fbce313fc1bf495699cc5d30135e1ff29e5f1d3045f85a36a68e4b6ba6ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
